eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password456@localhost:8761/eureka/
server:
  port: 8801
spring:
  application:
    name: service-zuul
zuul:
  routes:
    user:
      path: user/**
      service-id: service-ribbon
   
