server: 
  port: 80

logging:
  level:
    root: all
# redis相关属性
spring: 
  redis: 
    host: 182.61.30.187
    database: 0
    port: 6379
    password: 
    timeout: 5000 # 设置连接超时为5s
    pool: 
      # 最大空闲连接数
      max-idle: 8
      # 连接池最大连接数
      max-active: 8
      # -1 means no limit
      max-wait: -1
      # 最小空闲连接数
      min-idle: 0      
custom: 
  connection: 
    retry-time: 3   # 连接失败重试次数为3
    timeout: 5000   # 连接超时时间为5s