spring:
  resources:
    static-locations:
    - /static/
  freemarker:
    template-loader-path:
    - /WEB-INF/ftl/
  application:
    name: chinasofti-wxmgr-web
server:
  port: 7701
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:weixin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
   hystrix:
      enabled: false   