<<<<<<< HEAD
spring:
  resources:
    static-locations:
    - /static/
  freemarker:
    template-loader-path:
    - /WEB-INF/ftl/
  application:
    name: chinasofti-wxmgr-webService
server:
  port: 7902
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:weixin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
   hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMillseconds: 10000
enabled: false 
=======
spring:
  resources:
    static-locations:
    - /static/
  freemarker:
    template-loader-path:
    - /WEB-INF/ftl/
  application:
    name: chinasofti-wxmgr-webService
server:
  port: 7902
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:weixin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
   hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMillseconds: 10000
enabled: false 
>>>>>>> branch 'weixin' of https://github.com/lixhongwu/chinasoftibase.git
