spring:
  resources:
    static-locations:
    - /static/
  freemarker:
    template-loader-path:
    - /WEB-INF/ftl/
  application:
    name: microservice-consumer-movie
server:
  port: 7902
user: 
  userServicePath: http://localhost:7801/
  goodServicepath: http://localhost:7701/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    