server:
  port: 8080
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lixhongwu/chinasoftibase.git	#先 在github上创建一个对应的project
          #search-paths: config-repos/py-goodsorderService,config-repos/sp-goodsService
          search-paths: config-repos/**
  application:
    name: chinasofti-sp-config	# 配置文件就是用这个来做文件名的
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password456@localhost:8761/eureka
  instance:
    prefer-ip-address: true